import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

final data2 = [
  "MI CUENTA",
  "Nombre                                                     keanu_reeves",
  "Nombre de usuario                                               Keanu",
  "Fecha de nacimiento                                     2/8/1964",
  "Número de móvil                                         923564874",
  "Correo electrónico",
  "Snapchat+",
  "Contraseña",
  "Autenticación de dos factores",
  "Conexiones de socios",
  "Notificaciones",
  "Bitmoji",
  "Cameos",
  "Shazam",
  "Aolicaciones de Snap",
  "Idioma",
  "SERVICIOS ADICIONALES",
  "Administrar",
  "CONTROL DE PRIVACIDAD",
  "Contactame",
  "Ver Mi historia                                            solo amigos",
  "Verme en <<Añadido fácil>>",
  "Ver mi ubicación",
  "Recuerdos",
  "Lentes",
  "Spectacles",
  "Pixy",
  "Personalizar emojis",
  "Anuncios",
  "Ahorro de datos",
  "AYUDA",
  "Necesito ayuda",
  "Me preocupa un asunto de seguridad",
  "Tengo una pregunta sobre privacidad",
  "COMENTARIOS",
  "He encontrado un error",
  "Tengo una sugerencia",
  "Panel hecho para mi",
  "Agitar para informar",
  "MÁS INFORMACIÓN",
  "Política de privacidad",
  "Centro de seguridad",
  "Términos del servicio",
  "Otros textos legales",
  "ACCIONES DE CUENTA",
  "Borrar caché",
  "Borrar conversación",
  "Borrar historial de búsqueda",
  "Borrar historial de escaneo",
  "Borrar historial del escaner de voz",
  "Eliminar productos recientes",
  "Lugares",
  "Permisos",
  "Sincronización de contactos",
  "Bloqueado",
  "Información de inicio de sesión guardada",
  "Mis datos",
  "Cerrar sesión",
  "                      Snapchat versión 12.01.0.33\n                            Creado en Los Ángeles",
];
